version: 0.0
os: linux
files:
  - source: app.py
    destination: /opt/webapp/
  - source: .venv/
    destination: /opt/webapp/.venv/
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/applicationStart.sh
      timeout: 120
      runas: ec2-user
  ValidateService:
    - location: scripts/validateService.sh
      timeout: 120
      runas: ec2-user
  ApplicationStop:
    - location: scripts/applicationStop.sh
      timeout: 300
      runas: ec2-user