version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - yum update -y
      - yum install -y python3 pip3
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - python3 -m venv .venv
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - .venv/bin/pip3 install -r requirements.txt
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - .venv/**/*
    - scripts/**/*
    - app.py
    - appspec.yml
  name: helloworld-app-$(date +%Y%m%d%H%M%S).zip
  discard-paths: no